[package]
name = "TerminalToDo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dialoguer = "0.10.1"
platform-dirs = "0.3.0"
serde_json = "1.0"
serde = { version = "1.0.137", features = ["derive"] }